#!/usr/bin/perl

print "Content-type: text/html\n\n";
	print <<End_of_Head;
<HTML>
<TITLE>
Conexi&oacute;n a Arnet
</TITLE>
<BODY>
Intentando Conexi&oacute;n a Arnet ...
Por favor, espere un minuto ...
</BODY>
</HTML>
End_of_Head

$comando = "/root/scripts/arnet 1>/dev/null 2>&1 &";
system ("$comando");
exit;
