#!/usr/bin/perl

print "Content-type: text/html\n\n";
	print <<End_of_Head;
<HTML>
<TITLE>
Rebooteo de Servidor
</TITLE>
<BODY>
Rebooteando Servidor ...
Intente reconectarse en unos minutos ...
</BODY>
</HTML>
End_of_Head

$comando = "/sbin/reboot 1>/dev/null 2>&1 &";
system ("$comando");
exit;
